logLevel = "DEBUG"

[api]
dashboard = true

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "docker.localhost"
watch = true
exposedByDefault = false
swarmMode = false

[traefikLog]
  filePath = "/var/logs/traefik/traefik.log"

[accessLog]
  filePath = "/var/logs/traefik/access.log"

